### ISSUE TITLE
[ERROR] [label_studio_ml.model::get_result::59]

### ISSUE THREAD

**Issue by peidongha** [kieefuanh/LabelStudio-Yolov8-Detection-Backend#1]
Traceback (most recent call last):
  File "/home/zhangpeidong/Anaconda3/envs/label-studio-yolov8-Backend/lib/python3.10/site-packages/label_studio_ml/model.py", line 57, in get_result
    job_result = self.get_result_from_job_id(model_version)
  File "/home/zhangpeidong/Anaconda3/envs/label-studio-yolov8-Backend/lib/python3.10/site-packages/label_studio_ml/model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError

When I click on "start train", I get ”completions”as empty

**Comment by peidongha** [comment]
![Uploading img_v3_02fm_197cb1ac-97e3-4c73-9522-ba9fb444641g.jpg…]()
